on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongodb/mongodb-atlas-local:8.0
        volumes:
          - ./initdb.ci:/docker-entrypoint-initdb.d
        ports:
          - 27317:27017
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
      

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: pull embeddings model
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama pull mxbai-embed-large

      - name: check test data
        run: |
          curl --output mongosh.deb https://downloads.mongodb.com/compass/mongodb-mongosh_2.3.9_amd64.deb
          sudo dpkg -i mongosh.deb
          mongosh 'mongodb://localhost:27317/?directConnection=true' --eval 'show dbs'

      - name: run tests
        run: |
          cd app
          ./mvnw verify

